version: '3.8'

name: pim-dev

services:
  postgres-pim:
    image: postgres:15-alpine
    container_name: postgres-pim
    restart: unless-stopped
    environment:
      POSTGRES_USER: pim_user
      POSTGRES_PASSWORD: secure_password_change_me
      POSTGRES_DB: pim_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_pim_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pim_user -d pim_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pim-network

  redis-pim:
    image: redis:7-alpine
    container_name: redis-pim
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - pim-network

  elasticsearch-pim:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-pim
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - pim-network

volumes:
  postgres_pim_data:

networks:
  pim-network:
    driver: bridge
